apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes monitoring stack with Prometheus and Grafana

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "79.1.1"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "10.1.4"
    repository: "https://grafana.github.io/helm-charts"
